sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t sharangouda/docker-fib-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sharangouda/docker-fib-test npm run test

after_success:
  - docker build -t sharangouda/docker-fib-client ./client
  - docker build -t sharangouda/docker-fib-server ./server
  - docker build -t sharangouda/docker-fib-worker ./worker
  - docker build -t sharangouda/docker-fib-ngnix ./ngnix

#Login to docker CLI
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin

# Push to docker hub
  - docker push sharangouda/docker-fib-client 
  - docker push sharangouda/docker-fib-server 
  - docker push sharangouda/docker-fib-worker 
  - docker push sharangouda/docker-fib-ngnix 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-fibapp"
  env: "DockerFibapp-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-158213498601"
  bucket_path: "docker-fibapp"
  on:
    branch: master
  access_key_id: $AWS_FIBAPP_DEPLOY_KEY
  secret_access_key: $AWS_FIBAPP_DEPLOY_SEC
