sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t sharangouda/docker-fib -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sharangouda/react-fib npm run test

after_success:
  - docker build -t sharangouda/docker-fib-client ./client
  - docker build -t sharangouda/docker-fib-server ./server
  - docker build -t sharangouda/docker-fib-worker ./worker
  - docker build -t sharangouda/docker-fib-ngnix ./ngnix

#Login to docker CLI
- echo "DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin

# Push to docker hub
- dcoker push sharangouda/docker-fib-client 
- dcoker push sharangouda/docker-fib-server 
- dcoker push sharangouda/docker-fib-worker 
- dcoker push sharangouda/docker-fib-ngnix 
